{
 "title": "DORA metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Deployments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(dora_successful_deployments_total[14d]))*86400*14)/14",
     "legendFormat": "deployments per day over 2w"
    },
    {
     "expr": "sum(rate(dora_successful_deployments_total[1d]))*86400",
     "legendFormat": "deployments per day"
    },
    {
     "expr": "sum(rate(dora_failed_deployments_total[1d]))*86400",
     "legendFormat": "failed deployments per day"
    }
   ]
  },
  {
   "title": "Deployments per day (week on week)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(dora_successful_deployments_total[14d]))*86400*14)/14 - (sum(rate(dora_successful_deployments_total[14d] offset 1w))*86400*14)/14"
    }
   ]
  },
  {
   "title": "Deployments per day (over 2w)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(dora_successful_deployments_total[14d]))*86400*14)/14",
     "legendFormat": "successful deployments"
    }
   ]
  },
  {
   "title": "Cycle time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(dora_cycle_time_seconds[14d]))/60",
     "legendFormat": "Average cycle time (m) over 2w"
    },
    {
     "expr": "sum by (deployment) (avg_over_time(dora_cycle_time_seconds[12h]))/60",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Cycle time (week on week)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(dora_cycle_time_seconds)/60) - (avg(dora_cycle_time_seconds offset 1w)/60)"
    }
   ]
  },
  {
   "title": "Cycle time (m) over 2w",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(dora_cycle_time_seconds[14d]))/60",
     "legendFormat": "cycle time (m) over 2w"
    }
   ]
  },
  {
   "title": "Time to recovery",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(dora_time_to_recovery_seconds[2w]))/60",
     "legendFormat": "MTTR (m) over 2w"
    },
    {
     "expr": "sum by (deployment) (dora_time_to_recovery_seconds)/60",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Time to recovery (week on week)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dora_time_to_recovery_seconds)/60-avg(dora_time_to_recovery_seconds offset 1w)/60"
    }
   ]
  },
  {
   "title": "Time to recovery (m) over 2w",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(dora_time_to_recovery_seconds[2w]))/60"
    }
   ]
  },
  {
   "title": "Deployments by namespace (1d)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_namespace) (increase(dora_successful_deployments_total[1d]))",
     "legendFormat": "{{ .exported_namespace }}"
    }
   ]
  },
  {
   "title": "Deployments by workload (1d)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (increase(dora_successful_deployments_total[1d]))",
     "legendFormat": "{{ .deployment }}"
    }
   ]
  }
 ]
}